import React, { useState } from 'react';
import { Shield, CheckCircle, AlertTriangle, Clock, Download, Upload, FileText, Calendar } from 'lucide-react';
import { toast } from 'sonner';
import { downloadCSV, downloadBlob } from '../utils/download';
import { useCurrency } from '../context/CurrencyContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Progress } from './ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from './ui/table';
import { Alert, AlertDescription } from './ui/alert';
import { User, Organization } from '../App';

interface ComplianceManagementProps {
  currentUser: User;
  organization: Organization;
}

const filingSchedule = [
  { id: 'ESI-JUL', name: 'ESI Monthly Return', month: 'July 2025', dueDate: '2025-08-15', status: 'due', type: 'ESI', amount: 89500, daysLeft: 14 },
  { id: 'PF-JUL', name: 'PF Monthly Challan', month: 'July 2025', dueDate: '2025-08-20', status: 'due', type: 'PF', amount: 1567800, daysLeft: 19 },
  { id: 'TDS-JUL', name: 'TDS Challan (Salary)', month: 'July 2025', dueDate: '2025-08-07', status: 'overdue', type: 'TDS', amount: 234500, daysLeft: -1 },
  { id: 'PT-JUL', name: 'Professional Tax Return', month: 'July 2025', dueDate: '2025-08-15', status: 'due', type: 'PT', amount: 45600, daysLeft: 14 },
  { id: 'ESI-JUN', name: 'ESI Monthly Return', month: 'June 2025', dueDate: '2025-07-15', status: 'filed', type: 'ESI', amount: 87200, daysLeft: 0 },
  { id: 'PF-JUN', name: 'PF Monthly Challan', month: 'June 2025', dueDate: '2025-07-20', status: 'filed', type: 'PF', amount: 1543200, daysLeft: 0 },
  { id: 'TDS-JUN', name: 'TDS Challan (Salary)', month: 'June 2025', dueDate: '2025-07-07', status: 'filed', type: 'TDS', amount: 228700, daysLeft: 0 },
  { id: 'FORM24Q-Q1', name: 'Form 24Q - Q1 TDS Return', month: 'Q1 FY26', dueDate: '2025-07-31', status: 'filed', type: 'TDS', amount: 0, daysLeft: 0 },
];

const complianceChecks = [
  { category: 'Minimum Wage Compliance', score: 100, details: 'All employees paid above statutory minimum wage', status: 'excellent' },
  { category: 'Equal Remuneration Act', score: 98, details: 'Gender pay gap within acceptable limits', status: 'excellent' },
  { category: 'Payment of Wages Act', score: 100, details: 'Salaries credited within statutory timelines', status: 'excellent' },
  { category: 'Maternity Benefit Compliance', score: 100, details: 'All maternity benefits correctly computed', status: 'excellent' },
  { category: 'Gratuity Act Compliance', score: 97, details: '2 employees approaching gratuity eligibility threshold', status: 'good' },
  { category: 'Bonus Act Compliance', score: 96, details: 'Annual bonus calculations under review', status: 'good' },
  { category: 'Labour Welfare Fund', score: 100, details: 'LWF contributions up to date', status: 'excellent' },
  { category: 'ESIC Compliance', score: 98, details: 'Minor exceptions under review for contract staff', status: 'excellent' },
];

const auditItems = [
  { id: '1', description: 'ESI Return filed for June 2025', date: '2025-07-14', filedBy: 'Suresh Nair', status: 'confirmed' },
  { id: '2', description: 'PF Challan submitted - June 2025', date: '2025-07-19', filedBy: 'Meena Iyer', status: 'confirmed' },
  { id: '3', description: 'Form 24Q (Q1 FY26) filed with TRACES', date: '2025-07-30', filedBy: 'Vijay Sharma', status: 'confirmed' },
  { id: '4', description: 'TDS Q1 reconciliation completed', date: '2025-07-31', filedBy: 'Rajesh Kumar', status: 'confirmed' },
];

export function ComplianceManagement({ currentUser, organization }: ComplianceManagementProps) {
  const { fmtFull } = useCurrency();
  const [filings, setFilings] = useState(filingSchedule);

  const overallScore = Math.round(complianceChecks.reduce((s, c) => s + c.score, 0) / complianceChecks.length);
  const overdueCount = filings.filter(f => f.status === 'overdue').length;
  const dueCount = filings.filter(f => f.status === 'due').length;
  const filedCount = filings.filter(f => f.status === 'filed').length;

  const markFiled = (id: string) => {
    setFilings(prev => prev.map(f => f.id === id ? { ...f, status: 'filed', daysLeft: 0 } : f));
    const filing = filings.find(f => f.id === id);
    if (filing) toast.success(`${filing.name} filed successfully`, { description: `Marked as filed on ${new Date().toLocaleDateString('en-IN')}` });
  };

  const generateReturn = (type: string, name: string, amount: number) => {
    const rows = [{ 'Return Type': type, 'Period': 'July 2025', 'Amount (₹)': amount, 'Generated By': currentUser.name, 'Generated On': new Date().toLocaleDateString('en-IN'), 'Status': 'Generated' }];
    downloadCSV(rows, `${type}_Return_July_2025.csv`);
    toast.success(`${name} generated & downloaded`);
  };

  const downloadReceipt = (filing: typeof filings[0]) => {
    const content = `FILING RECEIPT\n\nFiling: ${filing.name}\nPeriod: ${filing.month}\nDue Date: ${filing.dueDate}\nAmount: ${fmtFull(filing.amount)}\nStatus: Filed\nGenerated: ${new Date().toLocaleDateString('en-IN')}\n\nThis is a system-generated receipt.`;
    downloadBlob(content, `Receipt_${filing.id}.txt`, 'text/plain');
    toast.success('Receipt downloaded');
  };

  const exportComplianceReport = () => {
    const rows = filings.map(f => ({
      'Filing': f.name, 'Period': f.month, 'Type': f.type, 'Due Date': f.dueDate,
      'Amount (₹)': f.amount, 'Status': f.status, 'Days Left': f.daysLeft,
    }));
    downloadCSV(rows, `Compliance_Report_${new Date().toLocaleDateString('en-CA')}.csv`);
    toast.success('Compliance report downloaded');
  };

  const statusBadge = (status: string, daysLeft: number) => {
    if (status === 'filed') return <Badge className="bg-green-100 text-green-800">Filed</Badge>;
    if (status === 'overdue') return <Badge className="bg-red-100 text-red-800">Overdue</Badge>;
    if (daysLeft <= 7) return <Badge className="bg-orange-100 text-orange-800">Due Soon ({daysLeft}d)</Badge>;
    return <Badge className="bg-yellow-100 text-yellow-800">Upcoming ({daysLeft}d)</Badge>;
  };

  const typeBadge = (type: string) => {
    const map: Record<string, string> = {
      ESI: 'bg-blue-100 text-blue-800',
      PF: 'bg-purple-100 text-purple-800',
      TDS: 'bg-orange-100 text-orange-800',
      PT: 'bg-teal-100 text-teal-800',
    };
    return <Badge className={map[type] || 'bg-gray-100 text-gray-800'}>{type}</Badge>;
  };

  const getScoreColor = (score: number) => {
    if (score >= 98) return 'text-green-600';
    if (score >= 95) return 'text-blue-600';
    if (score >= 90) return 'text-yellow-600';
    return 'text-red-600';
  };

  return (
    <div className="p-6 space-y-6 max-w-7xl">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Compliance Management</h1>
          <p className="text-muted-foreground">Statutory compliance, regulatory filings, and labour law adherence</p>
        </div>
        <div className="flex space-x-2">
          <Button variant="outline" onClick={exportComplianceReport}>
            <Download className="h-4 w-4 mr-2" />
            Compliance Report
          </Button>
        </div>
      </div>

      {overdueCount > 0 && (
        <Alert className="border-red-200 bg-red-50">
          <AlertTriangle className="h-4 w-4 text-red-600" />
          <AlertDescription className="text-red-800">
            <strong>{overdueCount} filing(s) overdue!</strong> Immediate action required to avoid penalties.
          </AlertDescription>
        </Alert>
      )}

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="bg-gradient-to-br from-green-50 to-green-100 border-green-200">
          <CardContent className="p-4 flex items-center justify-between">
            <div>
              <p className="text-sm text-green-600">Compliance Score</p>
              <p className="text-3xl font-bold text-green-700">{overallScore}%</p>
            </div>
            <Shield className="h-10 w-10 text-green-500" />
          </CardContent>
        </Card>
        <Card className="bg-gradient-to-br from-red-50 to-red-100 border-red-200">
          <CardContent className="p-4 flex items-center justify-between">
            <div>
              <p className="text-sm text-red-600">Overdue</p>
              <p className="text-3xl font-bold text-red-700">{overdueCount}</p>
            </div>
            <AlertTriangle className="h-10 w-10 text-red-500" />
          </CardContent>
        </Card>
        <Card className="bg-gradient-to-br from-yellow-50 to-yellow-100 border-yellow-200">
          <CardContent className="p-4 flex items-center justify-between">
            <div>
              <p className="text-sm text-yellow-600">Due This Month</p>
              <p className="text-3xl font-bold text-yellow-700">{dueCount}</p>
            </div>
            <Clock className="h-10 w-10 text-yellow-500" />
          </CardContent>
        </Card>
        <Card className="bg-gradient-to-br from-blue-50 to-blue-100 border-blue-200">
          <CardContent className="p-4 flex items-center justify-between">
            <div>
              <p className="text-sm text-blue-600">Filed This Month</p>
              <p className="text-3xl font-bold text-blue-700">{filedCount}</p>
            </div>
            <CheckCircle className="h-10 w-10 text-blue-500" />
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="filings">
        <TabsList>
          <TabsTrigger value="filings">Filing Schedule</TabsTrigger>
          <TabsTrigger value="checklist">Compliance Checklist</TabsTrigger>
          <TabsTrigger value="history">Filing History</TabsTrigger>
        </TabsList>

        <TabsContent value="filings">
          <Card>
            <CardHeader>
              <CardTitle>Statutory Filing Schedule</CardTitle>
              <CardDescription>Track all mandatory compliance filings and deadlines</CardDescription>
            </CardHeader>
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Filing</TableHead>
                    <TableHead>Period</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Due Date</TableHead>
                    <TableHead>Amount</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filings.map((filing) => (
                    <TableRow key={filing.id} className={filing.status === 'overdue' ? 'bg-red-50' : ''}>
                      <TableCell className="font-medium">{filing.name}</TableCell>
                      <TableCell>{filing.month}</TableCell>
                      <TableCell>{typeBadge(filing.type)}</TableCell>
                      <TableCell>
                        <div className="flex items-center space-x-2">
                          <Calendar className="h-3 w-3 text-muted-foreground" />
                          <span className={filing.status === 'overdue' ? 'text-red-600 font-medium' : ''}>{filing.dueDate}</span>
                        </div>
                      </TableCell>
                      <TableCell>{filing.amount > 0 ? fmtFull(filing.amount) : '—'}</TableCell>
                      <TableCell>{statusBadge(filing.status, filing.daysLeft)}</TableCell>
                      <TableCell>
                        {filing.status !== 'filed' ? (
                          <div className="flex space-x-1">
                            <Button size="sm" className="h-7" onClick={() => markFiled(filing.id)}>
                              <Upload className="h-3 w-3 mr-1" />
                              File Now
                            </Button>
                            <Button size="sm" variant="outline" className="h-7" onClick={() => generateReturn(filing.type, filing.name, filing.amount)}>
                              <FileText className="h-3 w-3 mr-1" />
                              Generate
                            </Button>
                          </div>
                        ) : (
                          <Button size="sm" variant="ghost" className="h-7" onClick={() => downloadReceipt(filing)}>
                            <Download className="h-3 w-3 mr-1" />
                            Receipt
                          </Button>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="checklist">
          <Card>
            <CardHeader>
              <CardTitle>Labour Law Compliance Checklist</CardTitle>
              <CardDescription>Regulatory compliance status across all applicable acts</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {complianceChecks.map((check) => (
                  <div key={check.category} className="p-4 border rounded-lg">
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center space-x-3">
                        {check.score >= 98 ? (
                          <CheckCircle className="h-5 w-5 text-green-500" />
                        ) : (
                          <AlertTriangle className="h-5 w-5 text-yellow-500" />
                        )}
                        <h4 className="font-medium">{check.category}</h4>
                      </div>
                      <span className={`text-lg font-bold ${getScoreColor(check.score)}`}>{check.score}%</span>
                    </div>
                    <Progress value={check.score} className="h-2 mb-2" />
                    <p className="text-sm text-muted-foreground">{check.details}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="history">
          <Card>
            <CardHeader>
              <CardTitle>Recent Filing Activity</CardTitle>
              <CardDescription>History of statutory filings and confirmations</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {auditItems.map((item) => (
                  <div key={item.id} className="flex items-center justify-between p-4 border rounded-lg">
                    <div className="flex items-center space-x-3">
                      <CheckCircle className="h-5 w-5 text-green-500" />
                      <div>
                        <p className="font-medium text-sm">{item.description}</p>
                        <p className="text-xs text-muted-foreground">Filed by {item.filedBy} on {item.date}</p>
                      </div>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Badge className="bg-green-100 text-green-800">Confirmed</Badge>
                      <Button size="sm" variant="ghost" className="h-7">
                        <Download className="h-3 w-3" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
